<?php

/**
 * BaseCopisimChoix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etudiant
 * @property integer $poste
 * @property integer $ordre
 * @property CopisimEtudiant $CopisimEtudiant
 * @property CopisimPoste $CopisimPoste
 * 
 * @method integer         getEtudiant()        Returns the current record's "etudiant" value
 * @method integer         getPoste()           Returns the current record's "poste" value
 * @method integer         getOrdre()           Returns the current record's "ordre" value
 * @method CopisimEtudiant getCopisimEtudiant() Returns the current record's "CopisimEtudiant" value
 * @method CopisimPoste    getCopisimPoste()    Returns the current record's "CopisimPoste" value
 * @method CopisimChoix    setEtudiant()        Sets the current record's "etudiant" value
 * @method CopisimChoix    setPoste()           Sets the current record's "poste" value
 * @method CopisimChoix    setOrdre()           Sets the current record's "ordre" value
 * @method CopisimChoix    setCopisimEtudiant() Sets the current record's "CopisimEtudiant" value
 * @method CopisimChoix    setCopisimPoste()    Sets the current record's "CopisimPoste" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimChoix extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_choix');
        $this->hasColumn('etudiant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poste', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ordre', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimEtudiant', array(
             'local' => 'etudiant',
             'foreign' => 'classement'));

        $this->hasOne('CopisimPoste', array(
             'local' => 'poste',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}