<?php

/**
 * BaseCopisimPoste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periode
 * @property integer $ville
 * @property integer $filiere
 * @property integer $total
 * @property CopisimPeriode $CopisimPeriode
 * @property CopisimItem $CopisimItem
 * 
 * @method integer        getPeriode()        Returns the current record's "periode" value
 * @method integer        getVille()          Returns the current record's "ville" value
 * @method integer        getFiliere()        Returns the current record's "filiere" value
 * @method integer        getTotal()          Returns the current record's "total" value
 * @method CopisimPeriode getCopisimPeriode() Returns the current record's "CopisimPeriode" value
 * @method CopisimItem    getCopisimItem()    Returns the current record's "CopisimItem" value
 * @method CopisimPoste   setPeriode()        Sets the current record's "periode" value
 * @method CopisimPoste   setVille()          Sets the current record's "ville" value
 * @method CopisimPoste   setFiliere()        Sets the current record's "filiere" value
 * @method CopisimPoste   setTotal()          Sets the current record's "total" value
 * @method CopisimPoste   setCopisimPeriode() Sets the current record's "CopisimPeriode" value
 * @method CopisimPoste   setCopisimItem()    Sets the current record's "CopisimItem" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimPoste extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_poste');
        $this->hasColumn('periode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ville', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filiere', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimPeriode', array(
             'local' => 'periode',
             'foreign' => 'id'));

        $this->hasOne('CopisimItem', array(
             'local' => 'filiere',
             'foreign' => 'id'));
    }
}