<?php

/**
 * Basecopisim_poste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periode
 * @property integer $ville
 * @property integer $filiere
 * @property integer $total
 * @property copisim_periode $copisim_periode
 * @property copisim_item $copisim_item
 * @property Doctrine_Collection $copisim_choix
 * 
 * @method integer             getPeriode()         Returns the current record's "periode" value
 * @method integer             getVille()           Returns the current record's "ville" value
 * @method integer             getFiliere()         Returns the current record's "filiere" value
 * @method integer             getTotal()           Returns the current record's "total" value
 * @method copisim_periode     getCopisimPeriode()  Returns the current record's "copisim_periode" value
 * @method copisim_item        getCopisimItem()     Returns the current record's "copisim_item" value
 * @method Doctrine_Collection getCopisimChoix()    Returns the current record's "copisim_choix" collection
 * @method copisim_poste       setPeriode()         Sets the current record's "periode" value
 * @method copisim_poste       setVille()           Sets the current record's "ville" value
 * @method copisim_poste       setFiliere()         Sets the current record's "filiere" value
 * @method copisim_poste       setTotal()           Sets the current record's "total" value
 * @method copisim_poste       setCopisimPeriode()  Sets the current record's "copisim_periode" value
 * @method copisim_poste       setCopisimItem()     Sets the current record's "copisim_item" value
 * @method copisim_poste       setCopisimChoix()    Sets the current record's "copisim_choix" collection
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecopisim_poste extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_poste');
        $this->hasColumn('periode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ville', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filiere', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('copisim_periode', array(
             'local' => 'periode',
             'foreign' => 'id'));

        $this->hasOne('copisim_item', array(
             'local' => 'filiere',
             'foreign' => 'id'));

        $this->hasMany('copisim_choix', array(
             'local' => 'id',
             'foreign' => 'poste'));
    }
}