<?php

/**
 * BaseCopisimFac
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periode
 * @property string $titre
 * @property CopisimPeriode $CopisimPeriode
 * @property Doctrine_Collection $CopisimEtudiant
 * @property Doctrine_Collection $CopisimReferent
 * 
 * @method integer             getPeriode()         Returns the current record's "periode" value
 * @method string              getTitre()           Returns the current record's "titre" value
 * @method CopisimPeriode      getCopisimPeriode()  Returns the current record's "CopisimPeriode" value
 * @method Doctrine_Collection getCopisimEtudiant() Returns the current record's "CopisimEtudiant" collection
 * @method Doctrine_Collection getCopisimReferent() Returns the current record's "CopisimReferent" collection
 * @method CopisimFac          setPeriode()         Sets the current record's "periode" value
 * @method CopisimFac          setTitre()           Sets the current record's "titre" value
 * @method CopisimFac          setCopisimPeriode()  Sets the current record's "CopisimPeriode" value
 * @method CopisimFac          setCopisimEtudiant() Sets the current record's "CopisimEtudiant" collection
 * @method CopisimFac          setCopisimReferent() Sets the current record's "CopisimReferent" collection
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimFac extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_fac');
        $this->hasColumn('periode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimPeriode', array(
             'local' => 'periode',
             'foreign' => 'id'));

        $this->hasMany('CopisimEtudiant', array(
             'local' => 'id',
             'foreign' => 'fac'));

        $this->hasMany('CopisimReferent', array(
             'local' => 'id',
             'foreign' => 'fac'));
    }
}