<?php

/**
 * BaseCopisimMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $exp
 * @property integer $dest
 * @property string $titre
 * @property string $texte
 * @property CopisimEtudiant $CopisimEtudiant
 * 
 * @method integer         getExp()             Returns the current record's "exp" value
 * @method integer         getDest()            Returns the current record's "dest" value
 * @method string          getTitre()           Returns the current record's "titre" value
 * @method string          getTexte()           Returns the current record's "texte" value
 * @method CopisimEtudiant getCopisimEtudiant() Returns the current record's "CopisimEtudiant" value
 * @method CopisimMessage  setExp()             Sets the current record's "exp" value
 * @method CopisimMessage  setDest()            Sets the current record's "dest" value
 * @method CopisimMessage  setTitre()           Sets the current record's "titre" value
 * @method CopisimMessage  setTexte()           Sets the current record's "texte" value
 * @method CopisimMessage  setCopisimEtudiant() Sets the current record's "CopisimEtudiant" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_message');
        $this->hasColumn('exp', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dest', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('titre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('texte', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimEtudiant', array(
             'local' => 'dest',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'desactivated' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}