<?php

/**
 * Basecopisim_etudiant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $prenom
 * @property integer $fac
 * @property date $naissance
 * @property string $email
 * @property boolean $anonyme
 * @property boolean $doublant
 * @property integer $classement
 * @property copisim_item $copisim_item
 * 
 * @method string           getNom()          Returns the current record's "nom" value
 * @method string           getPrenom()       Returns the current record's "prenom" value
 * @method integer          getFac()          Returns the current record's "fac" value
 * @method date             getNaissance()    Returns the current record's "naissance" value
 * @method string           getEmail()        Returns the current record's "email" value
 * @method boolean          getAnonyme()      Returns the current record's "anonyme" value
 * @method boolean          getDoublant()     Returns the current record's "doublant" value
 * @method integer          getClassement()   Returns the current record's "classement" value
 * @method copisim_item     getCopisimItem()  Returns the current record's "copisim_item" value
 * @method copisim_etudiant setNom()          Sets the current record's "nom" value
 * @method copisim_etudiant setPrenom()       Sets the current record's "prenom" value
 * @method copisim_etudiant setFac()          Sets the current record's "fac" value
 * @method copisim_etudiant setNaissance()    Sets the current record's "naissance" value
 * @method copisim_etudiant setEmail()        Sets the current record's "email" value
 * @method copisim_etudiant setAnonyme()      Sets the current record's "anonyme" value
 * @method copisim_etudiant setDoublant()     Sets the current record's "doublant" value
 * @method copisim_etudiant setClassement()   Sets the current record's "classement" value
 * @method copisim_etudiant setCopisimItem()  Sets the current record's "copisim_item" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecopisim_etudiant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_etudiant');
        $this->hasColumn('nom', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('prenom', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('fac', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('naissance', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('anonyme', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('doublant', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('classement', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('copisim_item', array(
             'local' => 'fac',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}