<?php

/**
 * BaseCopisimChoix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etudiant
 * @property integer $poste
 * @property integer $complement
 * @property integer $ordre
 * @property CopisimItem $CopisimItem
 * 
 * @method integer      getEtudiant()    Returns the current record's "etudiant" value
 * @method integer      getPoste()       Returns the current record's "poste" value
 * @method integer      getComplement()  Returns the current record's "complement" value
 * @method integer      getOrdre()       Returns the current record's "ordre" value
 * @method CopisimItem  getCopisimItem() Returns the current record's "CopisimItem" value
 * @method CopisimChoix setEtudiant()    Sets the current record's "etudiant" value
 * @method CopisimChoix setPoste()       Sets the current record's "poste" value
 * @method CopisimChoix setComplement()  Sets the current record's "complement" value
 * @method CopisimChoix setOrdre()       Sets the current record's "ordre" value
 * @method CopisimChoix setCopisimItem() Sets the current record's "CopisimItem" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimChoix extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_choix');
        $this->hasColumn('etudiant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poste', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('complement', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimItem', array(
             'local' => 'complement',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}