<?php

/**
 * Basecopisim_item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periode
 * @property string $type
 * @property string $titre
 * @property copisim_periode $copisim_periode
 * @property Doctrine_Collection $copisim_etudiant
 * @property Doctrine_Collection $copisim_poste
 * @property Doctrine_Collection $copisim_choix
 * @property Doctrine_Collection $copisim_flux
 * 
 * @method integer             getPeriode()          Returns the current record's "periode" value
 * @method string              getType()             Returns the current record's "type" value
 * @method string              getTitre()            Returns the current record's "titre" value
 * @method copisim_periode     getCopisimPeriode()   Returns the current record's "copisim_periode" value
 * @method Doctrine_Collection getCopisimEtudiant()  Returns the current record's "copisim_etudiant" collection
 * @method Doctrine_Collection getCopisimPoste()     Returns the current record's "copisim_poste" collection
 * @method Doctrine_Collection getCopisimChoix()     Returns the current record's "copisim_choix" collection
 * @method Doctrine_Collection getCopisimFlux()      Returns the current record's "copisim_flux" collection
 * @method copisim_item        setPeriode()          Sets the current record's "periode" value
 * @method copisim_item        setType()             Sets the current record's "type" value
 * @method copisim_item        setTitre()            Sets the current record's "titre" value
 * @method copisim_item        setCopisimPeriode()   Sets the current record's "copisim_periode" value
 * @method copisim_item        setCopisimEtudiant()  Sets the current record's "copisim_etudiant" collection
 * @method copisim_item        setCopisimPoste()     Sets the current record's "copisim_poste" collection
 * @method copisim_item        setCopisimChoix()     Sets the current record's "copisim_choix" collection
 * @method copisim_item        setCopisimFlux()      Sets the current record's "copisim_flux" collection
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecopisim_item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_item');
        $this->hasColumn('periode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('copisim_periode', array(
             'local' => 'periode',
             'foreign' => 'id'));

        $this->hasMany('copisim_etudiant', array(
             'local' => 'id',
             'foreign' => 'fac'));

        $this->hasMany('copisim_poste', array(
             'local' => 'id',
             'foreign' => 'filiere'));

        $this->hasMany('copisim_choix', array(
             'local' => 'id',
             'foreign' => 'complement'));

        $this->hasMany('copisim_flux', array(
             'local' => 'id',
             'foreign' => 'complement'));
    }
}