<?php

/**
 * Basecopisim_periode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property year $annee
 * @property date $debut_choix
 * @property date $fin_choix
 * @property Doctrine_Collection $copisim_item
 * @property Doctrine_Collection $copisim_poste
 * @property Doctrine_Collection $copisim_flux
 * 
 * @method year                getAnnee()         Returns the current record's "annee" value
 * @method date                getDebutChoix()    Returns the current record's "debut_choix" value
 * @method date                getFinChoix()      Returns the current record's "fin_choix" value
 * @method Doctrine_Collection getCopisimItem()   Returns the current record's "copisim_item" collection
 * @method Doctrine_Collection getCopisimPoste()  Returns the current record's "copisim_poste" collection
 * @method Doctrine_Collection getCopisimFlux()   Returns the current record's "copisim_flux" collection
 * @method copisim_periode     setAnnee()         Sets the current record's "annee" value
 * @method copisim_periode     setDebutChoix()    Sets the current record's "debut_choix" value
 * @method copisim_periode     setFinChoix()      Sets the current record's "fin_choix" value
 * @method copisim_periode     setCopisimItem()   Sets the current record's "copisim_item" collection
 * @method copisim_periode     setCopisimPoste()  Sets the current record's "copisim_poste" collection
 * @method copisim_periode     setCopisimFlux()   Sets the current record's "copisim_flux" collection
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecopisim_periode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_periode');
        $this->hasColumn('annee', 'year', null, array(
             'type' => 'year',
             'notnull' => true,
             ));
        $this->hasColumn('debut_choix', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('fin_choix', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('copisim_item', array(
             'local' => 'id',
             'foreign' => 'periode'));

        $this->hasMany('copisim_poste', array(
             'local' => 'id',
             'foreign' => 'periode'));

        $this->hasMany('copisim_flux', array(
             'local' => 'id',
             'foreign' => 'periode'));
    }
}