<?php

/**
 * Basecopisim_choix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $etudiant
 * @property integer $poste
 * @property integer $complement
 * @property integer $ordre
 * @property copisim_poste $copisim_poste
 * @property copisim_item $copisim_item
 * 
 * @method integer       getEtudiant()      Returns the current record's "etudiant" value
 * @method integer       getPoste()         Returns the current record's "poste" value
 * @method integer       getComplement()    Returns the current record's "complement" value
 * @method integer       getOrdre()         Returns the current record's "ordre" value
 * @method copisim_poste getCopisimPoste()  Returns the current record's "copisim_poste" value
 * @method copisim_item  getCopisimItem()   Returns the current record's "copisim_item" value
 * @method copisim_choix setEtudiant()      Sets the current record's "etudiant" value
 * @method copisim_choix setPoste()         Sets the current record's "poste" value
 * @method copisim_choix setComplement()    Sets the current record's "complement" value
 * @method copisim_choix setOrdre()         Sets the current record's "ordre" value
 * @method copisim_choix setCopisimPoste()  Sets the current record's "copisim_poste" value
 * @method copisim_choix setCopisimItem()   Sets the current record's "copisim_item" value
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecopisim_choix extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_choix');
        $this->hasColumn('etudiant', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('poste', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('complement', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ordre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('copisim_poste', array(
             'local' => 'poste',
             'foreign' => 'id'));

        $this->hasOne('copisim_item', array(
             'local' => 'complement',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}