<?php

/**
 * BaseCopisimRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periode
 * @property string $titre
 * @property CopisimPeriode $CopisimPeriode
 * @property Doctrine_Collection $CopisimPoste
 * 
 * @method integer             getPeriode()        Returns the current record's "periode" value
 * @method string              getTitre()          Returns the current record's "titre" value
 * @method CopisimPeriode      getCopisimPeriode() Returns the current record's "CopisimPeriode" value
 * @method Doctrine_Collection getCopisimPoste()   Returns the current record's "CopisimPoste" collection
 * @method CopisimRegion       setPeriode()        Sets the current record's "periode" value
 * @method CopisimRegion       setTitre()          Sets the current record's "titre" value
 * @method CopisimRegion       setCopisimPeriode() Sets the current record's "CopisimPeriode" value
 * @method CopisimRegion       setCopisimPoste()   Sets the current record's "CopisimPoste" collection
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCopisimRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('copisim_region');
        $this->hasColumn('periode', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CopisimPeriode', array(
             'local' => 'periode',
             'foreign' => 'id'));

        $this->hasMany('CopisimPoste', array(
             'local' => 'id',
             'foreign' => 'ville'));
    }
}