copisim_poste:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimPoste
    module:               copisim_poste
    prefix_path:          /copisim_poste
    column:               id
    with_wildcard_routes: true

copisim_fac:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimFac
    module:               copisim_fac
    prefix_path:          /copisim_fac
    column:               id
    with_wildcard_routes: true

copisim_etudiant:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimEtudiant
    module:               copisim_etudiant
    prefix_path:          /copisim_etudiant
    column:               id
    with_wildcard_routes: true

copisim_region:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimRegion
    module:               copisim_region
    prefix_path:          /copisim_region
    column:               id
    with_wildcard_routes: true

copisim_filiere:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimFiliere
    module:               copisim_filiere
    prefix_path:          /copisim_filiere
    column:               id
    with_wildcard_routes: true

copisim_periode:
  class: sfDoctrineRouteCollection
  options:
    model:                CopisimPeriode
    module:               copisim_periode
    prefix_path:          /session
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: copisim_periode, action: index }

#copisim_periode_list_create_poste:
#  url: /session/:id/ListCreatePoste
#  param: { module: copisim_periode, action: ListCreatePoste }
#  requirements:
#    method: post
#    id: \d+

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
