<?php

/**
 * CopisimChoix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */

class CopisimChoix extends BaseCopisimChoix
{
  public function save(Doctrine_Connection $conn = null)
	{
		if(null === $this->getEtudiant())
		  $this->setEtudiant(sfContext::getInstance()->getUser()->getGuardUser()->getUserName());

//		if($choix = Doctrine::getTable('CopisimChoix')->isAlreadySaved($this->getEtudiant(), $this->getPoste()))
//		{
//			$this = $choix;
//			$this->setOrdre('0');
//		}

		if(null === $this->getOrdre())
		{
			$this->setOrdre('1');
			Doctrine::getTable('CopisimChoix')->cascadeEtudiantChoixDown($this->getEtudiant());
		}

		return parent::save($conn);
	}

}
