<?php

/**
 * CopisimPeriode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    copisim
 * @subpackage model
 * @author     Pierre-FrançoisPilouAngrand
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CopisimPeriode extends BaseCopisimPeriode
{
  public function __toString()
  {
    return $this->getAnnee();
  }
}
