CopisimEtudiant:
  actAs:
    Timestampable: 
      created: { disabled: true }
      updated: { format: Y-m-d }
  columns:
    nom: { type: string(50), notnull: true }
    prenom: { type: string(50), notnull: true }
    fac: { type: integer, notnull: true }
    naissance: { type: date }
    email: { type: string(100), notnull: false }
    email_tmp: { type: string(100), notnull: false }
    anonyme: { type: boolean, notnull: true, default: 0 }
    annee: { type: enum, values: ['DCEM4', 'DCEM4 doublant', 'TCEM1'], default: 'DCEM4' }
    classement: { type: integer, notnull: true }
  relations:
    CopisimFac: { local: fac, foreign: id }

CopisimFac:
  columns:
    periode: { type: integer, notnull: true }
    titre: { type: string(255), notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }

CopisimRegion:
  columns:
    periode: { type: integer, notnull: true }
    titre: { type: string(255), notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }

CopisimFiliere:
  columns:
    periode: { type: integer, notnull: true }
    titre: { type: string(255), notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }

CopisimPeriode:
  columns:
    annee: { type: year, notnull: true }
    debut_choix: { type: date, notnull: true }
    fin_choix: { type: date, notnull: true }

CopisimPoste:
  columns:
    periode: { type: integer, notnull: true }
    ville: { type: integer, notnull: true }
    filiere: { type: integer, notnull: true }
    total: { type: integer, notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }
    CopisimRegion: { local: ville, foreign: id }
    CopisimFiliere: { local: filiere, foreign: id }

CopisimChoix:
  actAs:
    Timestampable: ~
  columns:
    etudiant: { type: integer, notnull: true }
    poste: { type: integer, notnull: true }
    ordre: { type: integer(2), notnull: true }
  relations:
    CopisimEtudiant: { local: etudiant, foreign: classement }
    CopisimPoste: { local: poste, foreign: id }

CopisimReferent:
  columns:
    periode: { type: integer, notnull: true }
    nom: { type: string(50), notnull: true }
    email: { type: string(100), notnull: true }
    tel: { type: string(10), notnull: false }
    divers: { type: string(256), notnull: false }
    fac: { type: integer, notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }
    CopisimFac: { local: fac, foreign: id }

CopisimMessage:
  actAs:
    Timestampable:
      updated: { desactivated: true }
  columns:
    exp: { type: integer, notnull: true }
    dest: { type: integer, notnull: true }
    titre: { type: string(50), notnull: true }
    texte: { type: string, notnull: true }
  relations:
    CopisimEtudiant: { local: exp, foreign: id }
    CopisimEtudiant: { local: dest, foreign: id }

CopisimSimulation:
  columns:
    etudiant: { type: integer, notnull: true }
    poste: { type: integer, notnull: false }
    reste: { type: integer (3), notnull: false }
  relations:
    CopisimEtudiant: { local: etudiant, foreign: classement }
    CopisimPoste: { local: poste, foreign: id }
