CopisimEtudiant:
  actAs:
    Timestampable: ~
  columns:
    nom: { type: string(50), notnull: true }
    prenom: { type: string(50), notnull: true }
    fac: { type: integer, notnull: true }
    naissance: { type: date }
    email: { type: string(100), notnull: true }
    email_tmp: { type: string(100), notnull: true }
    anonyme: { type: boolean, notnull: true, default: 0 }
    doublant: { type: boolean, notnull: true, default: 0 }
    classement: { type: integer, notnull: true }
  relations:
    CopisimItem: { local: fac, foreign: id }

CopisimItem:
#  actAs:
  columns:
    periode: { type: integer, notnull: true }
    type: { type: string(20), notnull: true }
    titre: { type: string(255), notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }

CopisimPeriode:
#  actAs:
  columns:
    annee: { type: year, notnull: true }
    debut_choix: { type: date, notnull: true }
    fin_choix: { type: date, notnull: true }

CopisimPoste:
#  actAs:
  columns:
    periode: { type: integer, notnull: true }
    ville: { type: integer, notnull: true }
    filiere: { type: integer, notnull: true }
    total: { type: integer, notnull: true }
  relations:
    CopisimPeriode: { local: periode, foreign: id }
    CopisimItem: { local: ville, foreign: id }
    CopisimItem: { local: filiere, foreign: id }

CopisimChoix:
  actAs:
    Timestampable: ~
  columns:
    etudiant: { type: integer, notnull: true }
    poste: { type: integer, notnull: true }
    complement: { type: integer, notnull: true }
    ordre: { type: integer, notnull: true }
  relations:
    copisim_poste: { local: poste, foreign: id }
    CopisimItem: { local: complement, foreign: id }

CopisimFlux:
#  actAs:
    columns:
      periode: { type: integer, notnull: true }
      ville: { type: integer, notnull: true }
      complement: { type: integer, notnull: true }
      total: { type: integer, notnull: true }
    relations:
      CopisimPeriode: { local: periode, foreign: id }
      CopisimItem: { local: ville, foreign: id }
      CopisimItem: { local: complement, foreign: id }

